### ISSUE TITLE
Can't log into existing Google account.

### ISSUE THREAD

**Issue by 1719pankaj** [Alex313031/Thorium-Android#15] opened 2023-10-18 14:16 UTC
**System Details**
 - OS: Android 13 Oneui 5
 - Thorium version 117.0.5938.157

**Problem**
When I try to log into the browser with my Google account for sync and stuff it throws me into adding a Google account instead of picking an existing one. And when I add, it says account already exists (obviously)

**Additional Notes**
I installed the thorium webview and browser both.

**Comment by Enderteck** [comment] 2023-10-18 14:21
Exact same problem here.

**Comment by ouzbirki** [comment] 2023-10-18 14:28
Duplicate of https://github.com/Alex313031/Thorium-Android/issues/6. See comment: https://github.com/Alex313031/Thorium-Android/issues/6#issuecomment-1759088748

> [bugs.chromium.org/p/chromium/issues/detail?id=677887](https://bugs.chromium.org/p/chromium/issues/detail?id=677887)
> 
> Google restricts login and synchronization of third-party versions, and there is currently no solution

**Closed as not planned** 2023-10-18 14:46 UTC
