### ISSUE TITLE
Thorium doesn't detect google account

### ISSUE THREAD

**Issue by Magnusretrotech** [Alex313031/Thorium-Android#41] opened 2024-01-28 13:31 UTC
**System Details**
 - OS: [Android 11]
 - Thorium Version [120.0.6099.235]

**Problem**
It doesn't detect my Google account and prompts me to add a Google account but if I do add an account it says "This account already exists on your device".

**Screenshots**
![photo_2024-01-28_13-28-04](https://github.com/Alex313031/Thorium-Android/assets/96993862/a8361641-2c0d-41ff-88be-f2fe26a679a2)
![photo_2024-01-28_13-28-09](https://github.com/Alex313031/Thorium-Android/assets/96993862/b0edfff5-85fb-4113-9386-5660a631b761)

**Additional Notes**
I can't use Thorium on Android until this is fixed because Chrome sync is very valuable to me. I am writing this on thorium for desktop.

**Comment by PsyNyde** [comment] 2024-01-28 13:44
duplicate of #37 . Discuss your issue there.

**Closed** 2024-09-02 05:50 UTC
