### ISSUE TITLE
App crashes on startup.

### ISSUE THREAD

**Issue by XieyilinMain** [Alex313031/Thorium-Android#70] opened 2024-11-25 06:28 UTC
**System Details**
 - OS: Android 14, HyperOS 1.0.12
 - Thorium Version 126.0.6478.246

**Problem**
App crashes on startup, when using thorium in the second time.  

**Screenshots**

**Additional Notes**

java.lang.UnsatisfiedLinkError: No implementation found for void J.N.MSkFYnu9(long, int, int, int[], int, long) (tried Java_J_N_MSkFYnu9 and Java_J_N_MSkFYnu9__JII_3IIJ) - is the library loaded, e.g. System.loadLibrary?
	at J.N.MSkFYnu9(Native Method)
	at org.chromium.components.safe_browsing.SafeBrowsingApiBridge.startUriLookupBySafeBrowsingApi(chromium-Thorium_Public.apk-stable-647824604:13)
	at vx.run(chromium-Thorium_Public.apk-stable-647824604:515)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by GreekPilot1** [comment] 2024-11-27 16:19
Same here

**Comment by dnchshrp** [comment] 2024-12-12 21:32
duplicate of #65

**Closed as not planned** 2024-12-13 00:10 UTC
